name: NCTL Scan Dockerfile Demo
run-name: ${{ github.actor }} has triggered Scan Action ğŸš€
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: nirmata/go-nctl@publish-report
          token: ${{ secrets.GH_TOKEN }} # Use the stored secret here
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build go-nctl
        run: |
          ls -l
          cd go-nctl
          make linux

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - Dockerfile
        run: nctl analyze git-repo --policies ./policy/ --publish --debug
  
      - run: echo "ğŸ This job's status is ${{ job.status }}."
